"""make status name non-unique

Revision ID: 2bf61a569a02
Revises: 71ac2fd703e5
Create Date: 2026-01-18 02:41:42.798376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf61a569a02'
down_revision: Union[str, Sequence[str], None] = '71ac2fd703e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('statuses_name_key'), 'statuses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('statuses_name_key'), 'statuses', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
