"""Add new tables for initiatives, actions, categories, statuses, action_types

Revision ID: 66231472e7ea
Revises: 50657c3bbdb3
Create Date: 2026-01-14 18:56:46.882637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66231472e7ea'
down_revision: Union[str, Sequence[str], None] = '50657c3bbdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS initiatives CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_users_email CASCADE')
    op.execute('DROP TABLE IF EXISTS users CASCADE')
    op.execute('DROP TABLE IF EXISTS categories CASCADE')
    op.execute('DROP TABLE IF EXISTS statuses CASCADE')
    op.execute('DROP TABLE IF EXISTS actions CASCADE')
    op.execute('DROP TABLE IF EXISTS action_types CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_types',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('action_types_pkey')),
                    sa.UniqueConstraint('name', name=op.f('action_types_name_key'),
                                        postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_table('actions',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('linked_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('action_type', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(timezone=True),
                              autoincrement=False, nullable=False),
                    sa.Column('image_url', sa.VARCHAR(length=512),
                              autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name=op.f('actions_user_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('actions_pkey'))
                    )
    op.create_table('statuses',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('statuses_pkey')),
                    sa.UniqueConstraint('name', name=op.f('statuses_name_key'), postgresql_include=[
                    ], postgresql_nulls_not_distinct=False)
                    )
    op.create_table('categories',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('categories_pkey')),
                    sa.UniqueConstraint('name', name=op.f('categories_name_key'), postgresql_include=[
                    ], postgresql_nulls_not_distinct=False)
                    )
    op.create_table('users',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), autoincrement=False, nullable=False),
                    sa.Column('firebase_user_id', sa.VARCHAR(
                        length=128), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.Column('photo_url', sa.VARCHAR(length=512),
                              autoincrement=False, nullable=True),
                    sa.Column('user_type', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('location', postgresql.JSON(astext_type=sa.Text()),
                              autoincrement=False, nullable=True),
                    sa.Column('social_links', postgresql.JSON(
                        astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
                    sa.UniqueConstraint('firebase_user_id', name=op.f(
                        'users_firebase_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('initiatives',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('action', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('category_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('goal', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('complete', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('link', sa.VARCHAR(length=512),
                              autoincrement=False, nullable=True),
                    sa.Column('priority', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('status_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f(
                        'initiatives_category_id_fkey')),
                    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f(
                        'initiatives_status_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('initiatives_pkey'))
                    )
    # ### end Alembic commands ###
