"""Add status type to status table

Revision ID: 71ac2fd703e5
Revises: 66231472e7ea
Create Date: 2026-01-18 02:27:50.167096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ac2fd703e5'
down_revision: Union[str, Sequence[str], None] = '66231472e7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column(
        'status_type', sa.String(length=100), nullable=True))
    # Set a default value for existing rows
    op.execute("UPDATE statuses SET status_type = 'Status'")
    # Alter the column to be NOT NULL
    op.alter_column('statuses', 'status_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('statuses', 'status_type')
    # ### end Alembic commands ###
