"""Initial migration

Revision ID: 7b2ac69fdbc5
Revises:
Create Date: 2026-01-13 02:35:24.867978

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7b2ac69fdbc5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
