"""Updates to actions schema

Revision ID: 7fc93afdc7e2
Revises: 2bf61a569a02
Create Date: 2026-01-21 00:10:13.334287

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fc93afdc7e2"
down_revision: str | Sequence[str] | None = "2bf61a569a02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("actions", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("actions", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
