"""stable migration

Revision ID: cd5788a7d2af
Revises:
Create Date: 2026-01-21 03:17:49.356056

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "cd5788a7d2af"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
